app:
  image: node:4
  command: "bash -c 'npm install & node video-searcher'"
  working_dir: /project
  volumes:
    - .:/project
  links:
    - redis
  ports:
    - "3033:3033"

redis:
  image: redis:3.0
  command: "bash -c 'redis-server --loglevel debug'"
  ports:
      - "6379:6379"

